jobs:
- name: self
  plan:
  - get: code
    params:
      depth: 1
  - load_var: matrix
    file: code/matrix.json
    format: json
  - across:
    - var: pipeline
      values: ((.:matrix.pipelines))
    do:
    - set_pipeline: ((pipeline))
      file: code/concourse.yml
      vars:
        repository: ((repository))
        concourse:  ((.:matrix.concourse))
        platforms:  ((.:matrix.platforms))
        pipeline:   ((.:pipeline))
      instance_vars:
        project:    ((.:pipeline.project))
        version:    ((.:pipeline.version))

resources:
- name: code
  type: git
  source:
    uri: https://github.com/encodeering/docker-base.git
