jobs:
- name: build
  plan:
  - in_parallel:
    - get: code
      params:
        depth: 1
    - get: dind
  - across:
    - var: env
      values:
      - ARCH="amd64"
      - ARCH="armhf"
      max_in_flight: 2
    do:
    - task: build
      privileged: true
      image: dind
      config:
        platform: linux
        params:
          REPOSITORY: ((repository))
          PROJECT: ((project))
          VERSION: ((version))
          DOCKER_USERNAME: ((docker.username))
          DOCKER_PASSWORD: ((docker.password))
        inputs:
        - name: code
        run:
          path: entrypoint.sh
          args:
          - bash
          - -cx
          - |
            set -euo pipefail
            export ((.:env))
            apt-get update
            apt-get install -y debian-archive-keyring debootstrap
            cd code
            ci.sh docker
            bash ./module.sh .                  ./setup.sh
            bash ./module.sh modules/${PROJECT} ./build.sh
            bash ./module.sh .                  ./release.sh

resources:
- name: code
  type: git
  source:
    uri: https://github.com/encodeering/docker-base.git
- name: dind
  type: registry-image
  source:
    repository: encodeering/concourse-dind
    tag: 0.1.12
