jobs:
- name: self
  plan:
  - in_parallel:
    - get: ci
      params:
        depth: 1
    - get: code
      params:
        depth: 1
  - load_var: matrix
    file: code/matrix.json
    format: json
  - across:
    - var: pipeline
      values: ((.:matrix.pipelines))
    do:
    - set_pipeline: ((pipeline))
      file: ci/modules/pipeline/docker.yml
      vars:
        git:
          uri: ((git.uri))
        repository: ((repository))
        concourse:  ((.:matrix.concourse))
        platforms:  ((.:matrix.platforms))
        pipeline:   ((.:pipeline))
      instance_vars:
        project:    ((.:pipeline.project))
        version:    ((.:pipeline.version))

resources:
- name: ci
  type: git
  source:
    uri: https://github.com/encodeering/docker-ci.git
- name: code
  type: git
  source:
    uri: ((git.uri))
